name: Sincronizar Faturas da Digital Grid

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script de sincronização
        env:
          DG_API_TOKEN: ${{ secrets.DG_API_TOKEN }}
          BITRIX_WEBHOOK: ${{ secrets.BITRIX_WEBHOOK }}
        run: |
          python sync_faturas.py
